[package]
name = "radior"
version = "0.2.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.0.5", features = ["derive"] }
cursive = "0.18.0"
cursive-markup = "0.3.0"
derive_more = "0.99.17"
libmpv = "2.0.1"
shellexpand = "2.1.0"
toml = "0.5.8"
url = "2.2.2"

[build-dependencies]
pkg-config = "0.3.19"
