[package]
name = "radior"
version = "0.1.0"
edition = "2018"

[dependencies]
toml = "0.5.8"
cursive = "0.16.3"
chrono = "0.4.19"
shellexpand = "2.1.0"
clap = { version = "3.0.0-rc.7", features=["derive"] }
url = "2.2.2"
cursive-markup = "0.2.0"

[build-dependencies]
bindgen = "0.59.0"
pkg-config = "0.3.19"
