[package]
name = "radior"
version = "0.2.0"
edition = "2018"

[dependencies]
chrono = "0.4.19"
clap = { version = "3.2.14", features = ["derive"] }
cursive_buffered_backend = "0.6.0"
derive_more = "0.99.17"
libmpv = "2.0.1"
shellexpand = "2.1.0"
toml = "0.5.9"
url = "2.2.2"

[dependencies.cursive]
version = "0.18.0"
default-features = false
features = ["termion-backend"]

[build-dependencies]
pkg-config = "0.3.25"
